export const MOLECULES = [
  { id: 'h2o', name: '水', formula: 'H2O', cid: 962, book: 'b1', note: '分散系与溶液' },
  { id: 'cl2', name: '氯气', formula: 'Cl2', cid: 24526, book: 'b1', note: '海水中的氯' },
  { id: 'hcl', name: '氯化氢', formula: 'HCl', cid: 313, book: 'b1', note: '氯气性质' },
  { id: 'nacl', name: '氯化钠', formula: 'NaCl', cid: 5234, book: 'b1', note: '粗盐 / 离子化合物' },
  { id: 'hclo', name: '次氯酸', formula: 'HClO', cid: 24341, book: 'b1', note: '次氯酸和次氯酸盐' },
  { id: 'so2', name: '二氧化硫', formula: 'SO2', cid: 1119, book: 'b1', note: '硫的氧化物' },
  { id: 'so3', name: '三氧化硫', formula: 'SO3', cid: 24640, book: 'b1', note: '硫的氧化物' },
  { id: 'h2so4', name: '硫酸', formula: 'H2SO4', cid: 1118, book: 'b1', note: '浓硫酸' },
  { id: 'nh3', name: '氨', formula: 'NH3', cid: 222, book: 'b1', note: '氨和铵盐' },
  { id: 'hno3', name: '硝酸', formula: 'HNO3', cid: 944, book: 'b1', note: '硝酸和硝酸盐' },
  { id: 'no2', name: '二氧化氮', formula: 'NO2', cid: 3032552, book: 'b1', note: '氮的氧化物' },
  { id: 'naoh', name: '氢氧化钠', formula: 'NaOH', cid: 14798, book: 'b2', note: '重要金属化合物' },
  { id: 'fe2o3', name: '氧化铁', formula: 'Fe2O3', cid: 518696, book: 'b2', note: '铁的化合物' },
  { id: 'ch4', name: '甲烷', formula: 'CH4', cid: 297, book: 'b2', note: '饱和烃' },
  { id: 'c2h4', name: '乙烯', formula: 'C2H4', cid: 6325, book: 'b2', note: '不饱和烃' },
  { id: 'c2h2', name: '乙炔', formula: 'C2H2', cid: 6326, book: 'b2', note: '不饱和烃' },
  { id: 'etoh', name: '乙醇', formula: 'C2H5OH', cid: 702, book: 'b2', note: '乙醇和乙酸' },
  { id: 'hoac', name: '乙酸', formula: 'CH3COOH', cid: 176, book: 'b2', note: '乙醇和乙酸' },
  { id: 'glucose', name: '葡萄糖', formula: 'C6H12O6', cid: 5793, book: 'b2', note: '糖、油脂和蛋白质' },
  { id: 'benzene', name: '苯', formula: 'C6H6', cid: 241, book: 'b5', note: '芳香烃' },
  { id: 'phenol', name: '苯酚', formula: 'C6H5OH', cid: 996, book: 'b5', note: '醇和酚' },
  { id: 'hcho', name: '甲醛', formula: 'HCHO', cid: 712, book: 'b5', note: '醛和酮' },
  { id: 'ch3cl', name: '氯甲烷', formula: 'CH3Cl', cid: 6327, book: 'b5', note: '卤代烃' },
  { id: 'co2', name: '二氧化碳', formula: 'CO2', cid: 280, book: 'b3', note: '反应热常见物种' },
  { id: 'o2', name: '氧气', formula: 'O2', cid: 977, book: 'b1', note: '氧化还原' },
  { id: 'h2', name: '氢气', formula: 'H2', cid: 783, book: 'b3', note: '工业合成氨相关' },
  { id: 'n2', name: '氮气', formula: 'N2', cid: 947, book: 'b3', note: '工业合成氨' },
  { id: 'i2', name: '碘', formula: 'I2', cid: 807, book: 'b1', note: '溴和碘的提取' },
  { id: 'br2', name: '溴', formula: 'Br2', cid: 24408, book: 'b1', note: '溴和碘的提取' }
]
